version: '3'
#DOCKER-COMPOSE UTILIZADO DURANTES O DESENVOLVIMENTO DA API
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-network

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
#      PGADMIN_DEFAULT_PASSWORD: "admin"
#    ports:
#      - "15432:80"
#    depends_on:
#      - postgres
#    networks:
#      - postgres-network

networks:
  postgres-network:
    driver: bridge