spring:
  datasource:
    url: ${POSTGRES_CONNECTION_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${SHOW_SQL:false}
    show-sql: ${SHOW_SQL:false}