apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  POSTGRES_DB: soat_modulo_2
  POSTGRES_CONNECTION_URL: 'jdbc:postgresql://postgres:5432/soat_modulo_2?useSSL=false'
  SPRING_PROFILES_ACTIVE: prd
  SHOW_SQL: "false"