apiVersion: v1
kind: Service
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  type: LoadBalancer
  selector:
    app: backend-api
  ports:
  - name: api-backend-port
    port: 8080
    targetPort: 8080
    protocol: TCP

