apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: msimoni/soat-modulo-2:latest
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
          limits:
            memory: 512Mi
            cpu: 1000m
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USERNAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: SPRING_PROFILES_ACTIVE
        - name: SHOW_SQL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: SHOW_SQL
        - name: POSTGRES_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: POSTGRES_CONNECTION_URL